Try to fix conflict:
       error: The option `fileSystems."/usr/bin".fsType' has conflicting definition values:
       - In `/nix/store/skzb00cq9vb43ryyr8dyzxlqmqmfy0ss-nixos-23.11/nixos/nixos/modules/tasks/filesystems/envfs.nix': "envfs"
       - In `/etc/nixos/machines/petrosilia/hardware-configuration.nix': "fuse.envfs"
       Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.